version: '3'

services:
  web:
    build: ./
    working_dir: /code/bakerydemo
    command: bash -c "python manage.py migrate --noinput && python manage.py load_initial_data && python manage.py update_index && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./wagtail:/code/wagtail:rw
      - ./bakerydemo:/code/bakerydemo:rw
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://wagtail:changeme@postgres/wagtail
      PYTHON_PATH: /code/wagtail:/code/bakerydemo
    depends_on:
      - db
  db:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: wagtail
      POSTGRES_DB: wagtail
      POSTGRES_PASSWORD: changeme
    restart: always
    expose:
      - "5432"